[tool.black]
line-length = 88
target-version = ["py310"]

[tool.ruff]
line-length = 88
target-version = "py310"
exclude = [
    "Arecibo-Line/notebooks",
    "docs",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
