name: CI (Python)

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.py"
      - "pyproject.toml"
      - "requirements*.txt"
      - ".github/workflows/python-ci.yml"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: tall_project.settings
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # verktøy for kvalitet
          pip install pytest pytest-cov ruff black mypy

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Format (black --check)
        run: |
          black --check .

      - name: Type-check (mypy)
        # dropp eller justér stier hvis du ikke bruker typer enda
        run: |
          mypy .

      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings \
                 --cov=. --cov-report=xml:coverage.xml \
                 --junitxml=test-results.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            test-results.xml
            coverage.xml
